// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "Registers a new user and returns an access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Creates a new user on the Matrix server",
                "parameters": [
                    {
                        "description": "User Registration",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ClientJsonRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created user",
                        "schema": {
                            "$ref": "#/definitions/main.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "User creation failed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates a user and returns an access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Logs a user into the Matrix server",
                "parameters": [
                    {
                        "description": "Login Credentials",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ClientJsonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully logged in",
                        "schema": {
                            "$ref": "#/definitions/main.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Login failed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{platform}/device/{device_name}/webhook": {
            "post": {
                "description": "Adds a webhook for a given device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Adds a webhook for a given device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform Name",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Name",
                        "name": "device_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Method",
                        "name": "method",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Webhook added successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing Bearer token",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{platform}/devices": {
            "post": {
                "description": "Registers a new device connection for the specified platform and establishes a websocket connection.\nThe websocket connection will:\n- Receive media/images from the platform bridge\n- Handle login synchronization events\n- Send existing active sessions if available\n- Close connection when receiving nil data (indicating end of session or error)\nHere are various platforms supported:\n'wa' (for WhatsApp)\n'signal' (for Signal)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Adds a device for a given platform",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform Name",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Device Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ClientBridgeJsonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully added device and established websocket connection",
                        "schema": {
                            "$ref": "#/definitions/main.DeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing Bearer token",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{platform}/list/devices": {
            "post": {
                "description": "Retrieves all active devices for the specified platform and user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Lists devices for a given platform",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform Name",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Device List Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ClientBridgeJsonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of devices",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing Bearer token",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{platform}/message/{contact}": {
            "post": {
                "description": "Sends a message to a contact through the specified platform bridge. The message can include text and optional file data.\nThe function validates and sanitizes all input fields according to the following rules:\n- Username: 3-32 characters, letters, numbers, and underscores only\n- Message: 1-4096 characters, cannot be empty\n- Device name: 2-20 characters, letters and numbers only\n- Contact: Valid E.164 phone number format (8-15 digits)\n- Platform: 2-20 characters, letters and numbers only",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Sends a message to a contact through a platform bridge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform Name (2-20 characters, letters and numbers only)",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Contact ID (E.164 phone number without the plus sign, 8-15 digits)",
                        "name": "contact",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Message Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ClientMessageJsonRequeset"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully\" example:{\"contact\":\"1234567890\",\"message\":\"Hello, world!\",\"status\":\"sent\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request - validation errors for username, message, device_name, platform, or contact",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing Bearer token",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to send message or internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ClientBridgeJsonRequest": {
            "description": "Request payload to bind a platform bridge to a user",
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "main.ClientJsonRequest": {
            "description": "Request payload for user login or registration",
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "securepassword123"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "main.ClientMessageJsonRequeset": {
            "type": "object"
        },
        "main.DeviceResponse": {
            "description": "Response payload for successful device addition. The websocket_url is used to establish a connection that: - Receives media/images from the platform bridge - Handles login synchronization events - Receives existing active sessions if available - Closes when receiving nil data (indicating end of session or error)",
            "type": "object",
            "properties": {
                "websocket_url": {
                    "type": "string",
                    "example": "ws://localhost:8080/ws/telegram/john_doe"
                }
            }
        },
        "main.ErrorResponse": {
            "description": "Response payload for error cases",
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "Username must be 3-32 characters"
                },
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "main.LoginResponse": {
            "description": "Response payload for successful login",
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "syt_YWxwaGE..."
                },
                "status": {
                    "type": "string",
                    "example": "logged in"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "ShortMesh API",
	Description:      "Represents a webhook structure with device name, URL, method, and timestamp",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
